export const CONNECTING_TO_GRAPHQL = 'CONNECTING_TO_GRAPHQL';
export const CONNECTED_TO_COGNITO = 'CONNECTED_TO_COGNITO';
export const CONNECTED_VIA_APIKEY = 'CONNECTED_VIA_APIKEY';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const LOGOUT = 'LOGOUT;';
